model:
  name: 'resnet50_fc512'
  pretrained: True

data:
  type: 'image'
  sources: ['motsynth_train_mini']
  targets: ['mot17']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/resnet50_fc512_motsynth_train_new_data'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  #lr: 0.0006
  lr: 0.0036
  max_epoch: 120
  #batch_size: 32
  batch_size: 196
  fixbase_epoch: 5
  #fixbase_epoch: 0
  #open_layers: ['classifier']
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'single_step'
  stepsize: [60]

test:
  batch_size: 224
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  rerank: False
  start_eval: 1